"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: nao revele a chave secreta em producao!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: nao rode com debug ligado em producao!
DEBUG = config("DEBUG", default=False, cast=bool)

# Em produção, mantenha False. Ative temporariamente para debugar respostas 500.
DEBUG_ERROR_DETAILS = config("DEBUG_ERROR_DETAILS", default=False, cast=bool)

# URL pública do frontend (usada em links de recuperação de senha e integrações web)
FRONTEND_URL = config("FRONTEND_URL", default="https://gaia-1-xmds.onrender.com")

# PRODUÇÃO: Adicione o domínio do servidor aqui
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1,gaia-2spq.onrender.com',
    cast=lambda v: [s.strip() for s in v.split(',') if s.strip()]
)

# Validação explícita de configuração em produção.
# Evita subir a aplicação com hosts inválidos ou ausentes.
if not DEBUG:
    assert ALLOWED_HOSTS, "ALLOWED_HOSTS deve ser configurado em produção"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps de terceiros
    'rest_framework',
    'corsheaders',
    'django_filters',

    # Minhas apps
    'report',
    'authentication',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'config.middleware.JWTCookieToHeaderMiddleware',  #  NOVO: Converte cookie → header
    'config.middleware.SecurityHeadersMiddleware',  # Headers de segurança customizados
]

# DESENVOLVIMENTO: URLs locais
if DEBUG:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:5000",
        "http://127.0.0.1:5000",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "https://gaia-2spq.onrender.com",
    ]
    CORS_ALLOW_ALL_ORIGINS = False
else:
    # PRODUÇÃO: Apenas origens específicas (CONFIGURAR NO .env)
    CORS_ALLOWED_ORIGINS = config(
        'CORS_ALLOWED_ORIGINS',
        default='https://gaia-1-xmds.onrender.com',
        cast=lambda v: [s.strip() for s in v.split(',') if s.strip()]
    )
    CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOW_CREDENTIALS = True

# CSRF_TRUSTED_ORIGINS: Confiar em requisições dessa origem para CSRF
# Essencial quando frontend está em origem diferente do backend
# Formato: ['https://example.com', 'https://www.example.com']
if DEBUG:
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:5173",      # Vite dev server (padrão)
        "http://127.0.0.1:5173",
        "http://localhost:5000",      # Alternativo
        "http://127.0.0.1:5000",
        "http://localhost:8000",      # Backend (para fazer requisições para si mesmo)
        "http://127.0.0.1:8000",
        "https://gaia-2spq.onrender.com",
    ]
else:
    # PRODUÇÃO: Apenas o domínio real (CONFIGURAR NO .env)
    # Exemplo: CSRF_TRUSTED_ORIGINS=https://www.seuprojeto.com.br,https://seuprojeto.com.br
    CSRF_TRUSTED_ORIGINS = config(
        'CSRF_TRUSTED_ORIGINS',
        default='https://gaia-1-xmds.onrender.com',
        cast=lambda v: [s.strip() for s in v.split(',') if s.strip()]
    )

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT"),
    }
}

REDIS_URL = config('REDIS_URL', default='').strip()

if DEBUG or not REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Media files configuration (APENAS para servir arquivos)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'MAX_PAGE_SIZE': 100,
}

SIMPLE_JWT = {
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_HEADER_TYPES': ('Bearer',),

    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # 1 hora
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # 7 dias
    'ROTATE_REFRESH_TOKENS': True,  # Gera novo refresh token a cada uso
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=120),  # 2 horas
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# Static files (CSS, JS, imagens do próprio Django)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Pastas de estáticos adicionais (desenvolvimento)
# Mantém compatibilidade mesmo se a pasta ainda não existir.
PROJECT_STATIC_DIR = BASE_DIR / 'static'
if PROJECT_STATIC_DIR.exists():
    STATICFILES_DIRS = [PROJECT_STATIC_DIR]

# ===============================================
# SEGURANÇA: httpOnly Cookies (Proteção contra XSS)
# ===============================================
# EM DESENVOLVIMENTO: Ativado para testar; em PRODUÇÃO: controlled by if not DEBUG
SESSION_COOKIE_HTTPONLY = True      #  Cookies inacessíveis via JavaScript
CSRF_COOKIE_HTTPONLY = False         #  Caso True quebra SPAs Com httpOnly
SESSION_COOKIE_SAMESITE = 'Lax'     #  Mitiga CSRF attacks
CSRF_COOKIE_SAMESITE = 'Lax'        #  Mitiga CSRF attacks

# Segurança para produção
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 ano
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

AUTH_USER_MODEL = 'authentication.Usuario'

SYNC_CONFIG = {
    'SQLITE_PATH': os.path.join(BASE_DIR, 'soil_analysis.db'),
    'PG_CONN_STRING': config("SYNC_PG_CONN_STRING", default='')  # Opcional em produção
}

# --- CONFIGURAÇÃO DE ENVIO DE E-MAIL REAL (GMAIL) ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config("EMAIL_HOST")  # <--- COLOQUE SEU EMAIL GMAIL
EMAIL_HOST_PASSWORD = config("EMAIL_PASSWORD")   # <--- COLOQUE A SENHA DE APP QUE O GOOGLE GEROU
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL") # <--- COLOQUE SEU EMAIL GMAIL
# ----------------------------------------------------

